package com.pemmob.katalogbuku.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF103287)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCE5FF)
val LightOnPrimaryContainer = Color(0xFF0A1F5C)
val LightSecondary = Color(0xFF3485FE)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightTertiary = Color(0xFFFED362)
val LightOnTertiary = Color(0xFF3A2A00)
val LightTertiaryContainer = Color(0xFFFFF1C2)
val LightBackground = Color(0xFFFCFBF9)
val LightOnBackground = Color(0xFF12172B)
val LightSurface = Color(0xFFFCFBF9)
val LightOnSurface = Color(0xFF12172B)
val LightSurfaceVariant = Color(0xFFE6E9F2)
val LightOnSurfaceVariant = Color(0xFF444B63)
val LightOutline = Color(0xFF7A8299)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFF9DEDC)
val LightOnErrorContainer = Color(0xFF410E0B)

// Dark Theme Colors
val DarkPrimary = Color(0xFFA9C1FF)
val DarkOnPrimary = Color(0xFF0A1F5C)
val DarkPrimaryContainer = Color(0xFF1B3FA3)
val DarkOnPrimaryContainer = Color(0xFFDCE5FF)
val DarkSecondary = Color(0xFF7DB0FF)
val DarkOnSecondary = Color(0xFF002B66)
val DarkTertiary = Color(0xFFFED362)
val DarkOnTertiary = Color(0xFF3A2A00)
val DarkTertiaryContainer = Color(0xFF5C4700)
val DarkBackground = Color(0xFF0B1226)
val DarkOnBackground = Color(0xFFE6E9F5)
val DarkSurface = Color(0xFF0B1226)
val DarkOnSurface = Color(0xFFE6E9F5)
val DarkSurfaceVariant = Color(0xFF1E2745)
val DarkOnSurfaceVariant = Color(0xFFC2C8DC)
val DarkOutline = Color(0xFF8E97B3)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFF9DEDC)